// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm2-ot7GkoMCUDDKgTgoFoy7Rh572FnWk',
    appId: '1:342361168868:web:51fa4da5835688ab8c45f1',
    messagingSenderId: '342361168868',
    projectId: 'trackit-2-5ccc1',
    authDomain: 'trackit-2-5ccc1.firebaseapp.com',
    storageBucket: 'trackit-2-5ccc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAxjdA_sH_mQDAoxWCvXMielNzHkQzCJA',
    appId: '1:342361168868:android:78feda7c1bc7c9bf8c45f1',
    messagingSenderId: '342361168868',
    projectId: 'trackit-2-5ccc1',
    storageBucket: 'trackit-2-5ccc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgEej-VQokV1s5tnFj62fsUCYZ91s4l1E',
    appId: '1:342361168868:ios:23f113617fcb950f8c45f1',
    messagingSenderId: '342361168868',
    projectId: 'trackit-2-5ccc1',
    storageBucket: 'trackit-2-5ccc1.firebasestorage.app',
    iosBundleId: 'com.sanikaa.trackit.trackit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgEej-VQokV1s5tnFj62fsUCYZ91s4l1E',
    appId: '1:342361168868:ios:23f113617fcb950f8c45f1',
    messagingSenderId: '342361168868',
    projectId: 'trackit-2-5ccc1',
    storageBucket: 'trackit-2-5ccc1.firebasestorage.app',
    iosBundleId: 'com.sanikaa.trackit.trackit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm2-ot7GkoMCUDDKgTgoFoy7Rh572FnWk',
    appId: '1:342361168868:web:472055f677f79a8a8c45f1',
    messagingSenderId: '342361168868',
    projectId: 'trackit-2-5ccc1',
    authDomain: 'trackit-2-5ccc1.firebaseapp.com',
    storageBucket: 'trackit-2-5ccc1.firebasestorage.app',
  );
}
